# Exposes FastAPI backend to the internet via a LoadBalancer
apiVersion: v1
kind: Service
metadata:
 name: fastapi-service
 labels:
  app: fastapi-app
spec:
 type: ClusterIP
 ports:
  - protocol: TCP
    port: 80                        # Port exposed outside the cluster
    targetPort: 8000                # Port the app listens on inside (check Dockerfile)
 selector:
  app: fastapi                      # Link the Service to pods with label 'app: fastapi'