scrape_configs:
  - job_name: 'api-server'
    static_configs:
      - targets: ['${API_IP}:9100']

  - job_name: 'scanner-server'
    static_configs:
      - targets: ['${SCANNER_IP}:9100']

  - job_name: 'jenkins-server'
    static_configs:
      - targets: ['${JENKINS_IP}:9100']

  - job_name: 'ansible-server'
    static_configs:
      - targets: ['${ANSIBLE_IP}:9100']